version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 87654321
    ports:
      - 5432:5432
    networks:
      - postgres-net


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "yuriluiz557@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - 8080:80
    networks:
      - postgres-net

networks:
  postgres-net:
    name: postgres-net




